# Profile information
name: Gabriel PL
title: Gabriel PL Webpage
description: > 
  Blog personal para subir artículos y mi vida diaria.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sad-bardeen-fb6ec7.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ""
      type: "recipes"
    values: 
      layout: "collection"
  - scope:
      path: ""
      type: "posts"
    values: 
      layout: "post"
  - scope: 
      path: ""
    values:
      layout: "default"


email: alu0101240374@ull.edu.es

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
exclude: [ vendor ]
include: [_pages]
