# Profile information
name: Gabriel PL
title: Gabriel PL Webpage
description: > # this means to ignore newlines until "baseurl:"
  Blog personal para subir artículos y mi vida diaria.
permalink: ':title/'
baseurl: "/jekyll-github-pages-y-netlify-alu0101240374" # the subpath of your site, e.g. /blog
url: "artemsheludko.pw" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ""
      type: "recipes"
    values: 
      layout: "collection"
  - scope:
      path: ""
      type: "posts"
    values: 
      layout: "post"
  - scope: 
      path: ""
    values:
      layout: "default"

    
# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: #Add your Github

# Contact form
email: alu0101240374@ull.edu.es

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
